[advisories]
ignore = [
    # https://rustsec.org/advisories/RUSTSEC-2021-0139 - ansi_term is Unmaintained
    # needs close https://github.com/tokio-rs/tracing/issues/2282 or release https://github.com/tokio-rs/tracing/pull/2287
    # possibly 0.3.16
    "RUSTSEC-2021-0139",
]
