name: Security audit (push)

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Audit check
        uses: GothenburgBitFactory/audit-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: 'RUSTSEC-2020-0071'
